import sys
import os
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), '..')))
import Aanlyze_Sleep as AS
import logging

logging.info("🚀 Analyzer [9] started...")

tickers = ['AARTIPHARM', 'ABDL', 'ABSLAMC', 'AEGISLOG', 'AGARWALEYE', 'AMBUJACEM', 'ANANTRAJ', 'ANTHEM', 'APOLLOTYRE', 'ARSSBL', 'ASHAPURMIN', 'ASTEC', 'ASTERDM', 'ATGL', 'ATHERENERG', 'AVL', 'BALUFORGE', 'BANCOINDIA', 'BANKBEES', 'BBOX', 'BERGEPAINT', 'BIKAJI', 'BLACKBUCK', 'BLUEJET', 'BLUESTONE', 'BORORENEW', 'CAPILLARY', 'CELLO', 'CGPOWER', 'CHOICEIN', 'COHANCE', 'CONCOR', 'DABUR', 'DLF', 'ELGIEQUIP', 'EMAMILTD', 'EUREKAFORB', 'FINCABLES', 'FIVESTAR', 'GALLANTT', 'GHCL', 'GMDCLTD', 'GODREJAGRO', 'GRANULES', 'GRAPHITE', 'HDBFS', 'HDFCLIFE', 'HEG', 'HEXT', 'ICICIPRULI', 'IIFL', 'INDGN', 'INDHOTEL', 'IRCTC', 'JBMA', 'JKIL', 'JKLAKSHMI', 'JSL', 'JSLL', 'JUBLFOOD', 'JUBLINGREA', 'JUNIORBEES', 'KALYANKJIL', 'KEC', 'KIMS', 'KIRIINDUS', 'LANDMARK', 'LICHSGFIN', 'MAHSEAMLES', 'MANYAVAR', 'MARATHON', 'MARICO', 'MINDACORP', 'NAVA', 'ORKLAINDIA', 'OSWALPUMPS', 'PARAS', 'PATANJALI', 'PGEL', 'PICCADIL', 'PNGJL', 'PREMEXPLN', 'PRICOLLTD', 'PROTEAN', 'QPOWER', 'RATEGAIN', 'RAYMONDREL', 'RKFORGE', 'ROSSTECH', 'RUBICON', 'SALZERELEC', 'SANDHAR', 'SCHNEIDER', 'SENORES', 'SHAKTIPUMP', 'SILVERTUC', 'SIRCA', 'SONACOMS', 'STUDDS', 'SUDEEPPHRM', 'SUNTV', 'SYNGENE', 'SYRMA', 'TANLA', 'TATACHEM', 'TATAINVEST', 'TATATECH', 'TDPOWERSYS', 'TEJASNET', 'TIPSMUSIC', 'TMB', 'TRANSRAILL', 'TRITURBINE', 'UPL', 'VARROC', 'VENUSREM', 'WELENT', 'WEWORK', 'YATHARTH', 'ZENSARTECH']#EX.Price.list(125, 150)
tickers = [t + '.NS' for t in tickers]

while True:
    AS.analyze_real_time(tickers)
    AS.wait_until_next_15_min()