import sys
import os
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), '..')))
import Aanlyze_Sleep as AS
import logging

logging.info("🚀 Analyzer [8] started...")

tickers = ['5PAISA', 'AADHARHFC', 'AARTIDRUGS', 'AARTIIND', 'ABCAPITAL', 'ADANI-RE', 'AFCONS', 'AKUMS', 'ARVIND', 'ARVINDFASN', 'ASKAUTOLTD', 'BALRAMCHIN', 'BESTAGRO', 'BIOCON', 'BIRET', 'BLS', 'CHAMBLFERT', 'CHANDAN', 'CIEINDIA', 'CMSINFO', 'COALINDIA', 'CRAMC', 'CSBBANK', 'CUPID', 'DBL', 'DEEPINDS', 'DELHIVERY', 'DYCL', 'EBGNG', 'ELECON', 'EMBASSY', 'EMSLIMITED', 'EPACKPEB', 'EUROPRATIK', 'EXIDEIND', 'FDC', 'FINOPB', 'FSL', 'GENESYS', 'GENUSPOWER', 'GICRE', 'GODIGIT', 'GOLDIAM', 'GRMOVER', 'GUJGASLTD', 'GVPIL', 'HAPPSTMNDS', 'HARIOMPIPE', 'HERITGFOOD', 'HINDCOPPER', 'HINDZINC', 'HPL', 'HSCL', 'HUBTOWN', 'ICIL', 'IGARASHI', 'IGIL', 'IIFLCAPS', 'INDIACEM', 'INDOTHAI', 'INDRAMEDCO', 'IONEXCHANG', 'ITI', 'JAINREC', 'JKTYRE', 'JSFB', 'JSWENERGY', 'KIOCL', 'KPEL', 'KPIGREEN', 'KRBL', 'LATENTVIEW', 'LENSKART', 'LTF', 'LTFOODS', 'M&MFIN', 'MAHLIFE', 'MANINDS', 'MASFIN', 'MAXESTATES', 'MBEL', 'MEDIASSIST', 'MEIL', 'MIDHANI', 'MINDSPACE', 'MOIL', 'NRBBEARING', 'NUVOCO', 'OIL', 'ORIENTTECH', 'PARAGMILK', 'PCBL', 'PFC', 'POONAWALLA', 'PRAJIND', 'PRAMARA', 'RAILTEL', 'RAYMOND', 'RBLBANK', 'REFEX', 'RVNL', 'SAATVIKGL', 'SANGHVIMOV', 'SARDAEN', 'SAREGAMA', 'SENCO', 'SGFIN', 'SGMART', 'SHILPAMED', 'SHREEJISPG', 'SKYGOLD', 'SMARTWORKS', 'SMSPHARMA', 'SONATSOFTW', 'STARHEALTH', 'STYL', 'SUMICHEM', 'SUPRAJIT', 'SWANCORP', 'TAJGVK', 'TATACAP', 'TATAPOWER', 'TENNIND', 'THELEELA', 'THYROCARE', 'TI', 'TRUALT', 'USHAMART', 'VBL', 'VGUARD', 'VINSYS', 'VIPIND', 'VLSFINANCE', 'ZAGGLE']#EX.Price.list(100, 125)
tickers = [t + '.NS' for t in tickers]

while True:
    AS.analyze_real_time(tickers)
    AS.wait_until_next_15_min()