import sys
import os
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), '..')))
import Aanlyze_Sleep as AS
import logging

logging.info("🚀 Analyzer [10] started...")

tickers = ['360ONE', '63MOONS', 'ADANIENSOL', 'ADANIGREEN', 'AETHER', 'ANURAS', 'ARE&M', 'ASAHIINDIA', 'ASTRAL', 'ASTRAMICRO', 'ATLANTAELE', 'AUBANK', 'AUROPHARMA', 'AVALON', 'AVANTIFEED', 'BATAINDIA', 'BHARATFORG', 'BRIGADE', 'CANFINHOME', 'CARBORUNIV', 'CASHIETF', 'CCL', 'CEMPRO', 'CHALET', 'CHENNPETRO', 'CLEAN', 'CREDITACC', 'CYIENT', 'DEEPAKFERT', 'DREDGECORP', 'DRREDDY', 'EIDPARRY', 'EMCURE', 'FORTIS', 'GABRIEL', 'GESHIP', 'GMBREW', 'GODREJCP', 'GOKEX', 'HAVELLS', 'HBLENGINE', 'HINDALCO', 'HOMEFIRST', 'IMFA', 'INDIAGLYCO', 'INDIANB', 'INDUSINDBK', 'INOXINDIA', 'INTELLECT', 'IPCALAB', 'JINDALSTEL', 'JSWSTEEL', 'JYOTICNC', 'KAJARIACER', 'KERNEX', 'KFINTECH', 'KPITTECH', 'KPRMILL', 'LAURUSLABS', 'LICI', 'LIQUID', 'LIQUID1', 'LIQUIDADD', 'LIQUIDBEES', 'LIQUIDBETF', 'LIQUIDIETF', 'LLOYDSME', 'LODHA', 'MAXHEALTH', 'MEDANTA', 'MGL', 'MIDWESTLTD', 'MOTILALOFS', 'NAM-INDIA', 'NAUKRI', 'NESTLEIND', 'NEWGEN', 'OLECTRA', 'PAYTM', 'PIDILITIND', 'PNBHOUSING', 'POCL', 'PREMIERENE', 'PVRINOX', 'RPEL', 'SBICARD', 'SHARDACROP', 'SIGNATURE', 'STAR', 'SUBROS', 'TATACONSUM', 'TECHNOE', 'TITAGARH', 'TORNTPOWER', 'UNITDSPR', 'UNIVCABLES', 'UNOMINDA', 'VOLTAS', 'WAAREERTL', 'WABAG', 'WELCORP', 'WHIRLPOOL', 'ZENTEC', 'ZYDUSLIFE']#EX.Price.list(150, 175)
tickers = [t + '.NS' for t in tickers]

while True:
    AS.analyze_real_time(tickers)
    AS.wait_until_next_15_min()