import sys
import os
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), '..')))
import Aanlyze_Sleep as AS
import logging

logging.info("🚀 Analyzer [7] started...")

tickers = ['ACMESOLAR', 'ADVENTHTL', 'AEGISVOPAK', 'ANNAPURNA', 'APEX', 'APTUS', 'ARTEMISMED', 'AUTOBEES', 'AWL', 'BAJAJCON', 'BLSE', 'CAMPUS', 'CAPACITE', 'CRIZAC', 'CROMPTON', 'CUB', 'DAMCAPITAL', 'DCAL', 'DEEDEV', 'DELPHIFX', 'DIFFNKG', 'EEPL', 'EFCIL', 'EIEL', 'EPACK', 'EPL', 'ESFL', 'FABTECH', 'FIRSTCRY', 'FLAIR', 'GARUDA', 'GOKULAGRO', 'GPIL', 'HDFCNIFTY', 'HIKAL', 'HONASA', 'HUDCO', 'HUHTAMAKI', 'INDOSTAR', 'INOXGREEN', 'IRMENERGY', 'ITCHOTELS', 'IVALUE', 'IXIGO', 'JSWINFRA', 'JUNIPER', 'JWL', 'JYOTHYLAB', 'KANSAINER', 'KARURVYSYA', 'KITEX', 'LAXMIDENTL', 'LGHL', 'MANAPPURAM', 'MARINE', 'MID150BEES', 'MOBIKWIK', 'MON100', 'MOSCHIP', 'NAZARA', 'NIFTY1', 'NIFTYIETF', 'NLCINDIA', 'NORTHARC', 'NYKAA', 'PACEDIGITK', 'PATELRMART', 'PENIND', 'PETRONET', 'PINELABS', 'PLATIND', 'PNCINFRA', 'PRECWIRE', 'QUADFUTURE', 'QUESS', 'RALLIS', 'REDINGTON', 'RELIGARE', 'RESPONIND', 'RITCO', 'RITES', 'SANDUMA', 'SAPPHIRE', 'SARTELE', 'SAWALIYA', 'SEQUENT', 'SETFNIF50', 'SHALBY', 'SHANTIGOLD', 'SHRINGARMS', 'SIGNPOST', 'SIMPLEXINF', 'SOUTHWEST', 'SPANDANA', 'STANLEY', 'STARCEMENT', 'SULA', 'SURAJEST', 'SURYAROSNI', 'SWARAJ', 'SWSOLAR', 'TARIL', 'TARSONS', 'UTLSOLAR', 'VAIBHAVGBL', 'VERANDA', 'VIKRAMSOLR', 'VRLLOG', 'VSTIND']#EX.Price.list(80, 100)
tickers = [t + '.NS' for t in tickers]

while True:
    AS.analyze_real_time(tickers)
    AS.wait_until_next_15_min()